// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/dfs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A generic response for operations that just need to say "Success" or "Error"
type StandardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	mi := &file_proto_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *StandardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StandardResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Represents a list of Worker Node IP addresses
type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerIps     []string               `protobuf:"bytes,1,rep,name=worker_ips,json=workerIps,proto3" json:"worker_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_proto_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *NodeList) GetWorkerIps() []string {
	if x != nil {
		return x.WorkerIps
	}
	return nil
}

// The raw bytes for streaming 64MB files
type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_proto_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkData) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_proto_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CreateFileRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type CreateFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maps a ChunkID (e.g., "chunk-123") to a list of Worker IPs (e.g., ["192.168.1.5:8001", "192.168.1.6:8002"])
	ChunkLocations map[string]*NodeList `protobuf:"bytes,1,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_proto_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFileResponse) GetChunkLocations() map[string]*NodeList {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

type CommitFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilePath       string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ChunkIds       []string               `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	ChunkLocations map[string]*NodeList   `protobuf:"bytes,3,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitFileRequest) Reset() {
	*x = CommitFileRequest{}
	mi := &file_proto_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitFileRequest) ProtoMessage() {}

func (x *CommitFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitFileRequest.ProtoReflect.Descriptor instead.
func (*CommitFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *CommitFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CommitFileRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *CommitFileRequest) GetChunkLocations() map[string]*NodeList {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type GetFileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkLocations map[string]*NodeList   `protobuf:"bytes,1,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileResponse) GetChunkLocations() map[string]*NodeList {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

type HeartbeatMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	DiskUsage      int64                  `protobuf:"varint,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	DiskCapacity   int64                  `protobuf:"varint,4,opt,name=disk_capacity,json=diskCapacity,proto3" json:"disk_capacity,omitempty"`
	StoredChunkIds []string               `protobuf:"bytes,5,rep,name=stored_chunk_ids,json=storedChunkIds,proto3" json:"stored_chunk_ids,omitempty"` // The Master uses this to verify the Worker hasn't lost data
	RackId         string                 `protobuf:"bytes,6,opt,name=rack_id,json=rackId,proto3" json:"rack_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	mi := &file_proto_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatMsg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatMsg) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartbeatMsg) GetDiskUsage() int64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *HeartbeatMsg) GetDiskCapacity() int64 {
	if x != nil {
		return x.DiskCapacity
	}
	return 0
}

func (x *HeartbeatMsg) GetStoredChunkIds() []string {
	if x != nil {
		return x.StoredChunkIds
	}
	return nil
}

func (x *HeartbeatMsg) GetRackId() string {
	if x != nil {
		return x.RackId
	}
	return ""
}

type RetrieveChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveChunkRequest) Reset() {
	*x = RetrieveChunkRequest{}
	mi := &file_proto_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveChunkRequest) ProtoMessage() {}

func (x *RetrieveChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveChunkRequest.ProtoReflect.Descriptor instead.
func (*RetrieveChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *RetrieveChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

var File_proto_dfs_proto protoreflect.FileDescriptor

const file_proto_dfs_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/dfs.proto\x12\x03dfs\"Q\n" +
	"\x10StandardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\")\n" +
	"\bNodeList\x12\x1d\n" +
	"\n" +
	"worker_ips\x18\x01 \x03(\tR\tworkerIps\":\n" +
	"\tChunkData\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"M\n" +
	"\x11CreateFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\"\xbc\x01\n" +
	"\x12CreateFileResponse\x12T\n" +
	"\x0fchunk_locations\x18\x01 \x03(\v2+.dfs.CreateFileResponse.ChunkLocationsEntryR\x0echunkLocations\x1aP\n" +
	"\x13ChunkLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.dfs.NodeListR\x05value:\x028\x01\"\xf4\x01\n" +
	"\x11CommitFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\x12S\n" +
	"\x0fchunk_locations\x18\x03 \x03(\v2*.dfs.CommitFileRequest.ChunkLocationsEntryR\x0echunkLocations\x1aP\n" +
	"\x13ChunkLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.dfs.NodeListR\x05value:\x028\x01\"-\n" +
	"\x0eGetFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\xb6\x01\n" +
	"\x0fGetFileResponse\x12Q\n" +
	"\x0fchunk_locations\x18\x01 \x03(\v2(.dfs.GetFileResponse.ChunkLocationsEntryR\x0echunkLocations\x1aP\n" +
	"\x13ChunkLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.dfs.NodeListR\x05value:\x028\x01\"\xc8\x01\n" +
	"\fHeartbeatMsg\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x03R\tdiskUsage\x12#\n" +
	"\rdisk_capacity\x18\x04 \x01(\x03R\fdiskCapacity\x12(\n" +
	"\x10stored_chunk_ids\x18\x05 \x03(\tR\x0estoredChunkIds\x12\x17\n" +
	"\arack_id\x18\x06 \x01(\tR\x06rackId\"1\n" +
	"\x14RetrieveChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId2\x85\x02\n" +
	"\rMasterService\x12=\n" +
	"\n" +
	"CreateFile\x12\x16.dfs.CreateFileRequest\x1a\x17.dfs.CreateFileResponse\x12;\n" +
	"\n" +
	"CommitFile\x12\x16.dfs.CommitFileRequest\x1a\x15.dfs.StandardResponse\x12=\n" +
	"\x10GetFileLocations\x12\x13.dfs.GetFileRequest\x1a\x14.dfs.GetFileResponse\x129\n" +
	"\rSendHeartbeat\x12\x11.dfs.HeartbeatMsg\x1a\x15.dfs.StandardResponse2\x84\x01\n" +
	"\rWorkerService\x125\n" +
	"\n" +
	"StoreChunk\x12\x0e.dfs.ChunkData\x1a\x15.dfs.StandardResponse(\x01\x12<\n" +
	"\rRetrieveChunk\x12\x19.dfs.RetrieveChunkRequest\x1a\x0e.dfs.ChunkData0\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_dfs_proto_rawDescOnce sync.Once
	file_proto_dfs_proto_rawDescData []byte
)

func file_proto_dfs_proto_rawDescGZIP() []byte {
	file_proto_dfs_proto_rawDescOnce.Do(func() {
		file_proto_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dfs_proto_rawDesc), len(file_proto_dfs_proto_rawDesc)))
	})
	return file_proto_dfs_proto_rawDescData
}

var file_proto_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_dfs_proto_goTypes = []any{
	(*StandardResponse)(nil),     // 0: dfs.StandardResponse
	(*NodeList)(nil),             // 1: dfs.NodeList
	(*ChunkData)(nil),            // 2: dfs.ChunkData
	(*CreateFileRequest)(nil),    // 3: dfs.CreateFileRequest
	(*CreateFileResponse)(nil),   // 4: dfs.CreateFileResponse
	(*CommitFileRequest)(nil),    // 5: dfs.CommitFileRequest
	(*GetFileRequest)(nil),       // 6: dfs.GetFileRequest
	(*GetFileResponse)(nil),      // 7: dfs.GetFileResponse
	(*HeartbeatMsg)(nil),         // 8: dfs.HeartbeatMsg
	(*RetrieveChunkRequest)(nil), // 9: dfs.RetrieveChunkRequest
	nil,                          // 10: dfs.CreateFileResponse.ChunkLocationsEntry
	nil,                          // 11: dfs.CommitFileRequest.ChunkLocationsEntry
	nil,                          // 12: dfs.GetFileResponse.ChunkLocationsEntry
}
var file_proto_dfs_proto_depIdxs = []int32{
	10, // 0: dfs.CreateFileResponse.chunk_locations:type_name -> dfs.CreateFileResponse.ChunkLocationsEntry
	11, // 1: dfs.CommitFileRequest.chunk_locations:type_name -> dfs.CommitFileRequest.ChunkLocationsEntry
	12, // 2: dfs.GetFileResponse.chunk_locations:type_name -> dfs.GetFileResponse.ChunkLocationsEntry
	1,  // 3: dfs.CreateFileResponse.ChunkLocationsEntry.value:type_name -> dfs.NodeList
	1,  // 4: dfs.CommitFileRequest.ChunkLocationsEntry.value:type_name -> dfs.NodeList
	1,  // 5: dfs.GetFileResponse.ChunkLocationsEntry.value:type_name -> dfs.NodeList
	3,  // 6: dfs.MasterService.CreateFile:input_type -> dfs.CreateFileRequest
	5,  // 7: dfs.MasterService.CommitFile:input_type -> dfs.CommitFileRequest
	6,  // 8: dfs.MasterService.GetFileLocations:input_type -> dfs.GetFileRequest
	8,  // 9: dfs.MasterService.SendHeartbeat:input_type -> dfs.HeartbeatMsg
	2,  // 10: dfs.WorkerService.StoreChunk:input_type -> dfs.ChunkData
	9,  // 11: dfs.WorkerService.RetrieveChunk:input_type -> dfs.RetrieveChunkRequest
	4,  // 12: dfs.MasterService.CreateFile:output_type -> dfs.CreateFileResponse
	0,  // 13: dfs.MasterService.CommitFile:output_type -> dfs.StandardResponse
	7,  // 14: dfs.MasterService.GetFileLocations:output_type -> dfs.GetFileResponse
	0,  // 15: dfs.MasterService.SendHeartbeat:output_type -> dfs.StandardResponse
	0,  // 16: dfs.WorkerService.StoreChunk:output_type -> dfs.StandardResponse
	2,  // 17: dfs.WorkerService.RetrieveChunk:output_type -> dfs.ChunkData
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_dfs_proto_init() }
func file_proto_dfs_proto_init() {
	if File_proto_dfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dfs_proto_rawDesc), len(file_proto_dfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_dfs_proto_goTypes,
		DependencyIndexes: file_proto_dfs_proto_depIdxs,
		MessageInfos:      file_proto_dfs_proto_msgTypes,
	}.Build()
	File_proto_dfs_proto = out.File
	file_proto_dfs_proto_goTypes = nil
	file_proto_dfs_proto_depIdxs = nil
}
