// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/fractal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A generic response for operations that just need to say "Success" or "Error"
type StandardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	mi := &file_proto_fractal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{0}
}

func (x *StandardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StandardResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Represents a list of Worker Node IP addresses
type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerIps     []string               `protobuf:"bytes,1,rep,name=worker_ips,json=workerIps,proto3" json:"worker_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_proto_fractal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{1}
}

func (x *NodeList) GetWorkerIps() []string {
	if x != nil {
		return x.WorkerIps
	}
	return nil
}

// The raw bytes for streaming 64MB files
type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_proto_fractal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkData) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Client -> NameNode
type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_proto_fractal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CreateFileRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

// NameNode -> Client
type CreateFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maps a ChunkID (e.g., "chunk-123") to a list of Worker IPs (e.g., ["192.168.1.5:8001", "192.168.1.6:8002"])
	ChunkLocations map[string]*NodeList `protobuf:"bytes,1,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_proto_fractal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFileResponse) GetChunkLocations() map[string]*NodeList {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

// Client -> NameNode
type CommitFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilePath       string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ChunkIds       []string               `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	ChunkLocations map[string]*NodeList   `protobuf:"bytes,3,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitFileRequest) Reset() {
	*x = CommitFileRequest{}
	mi := &file_proto_fractal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitFileRequest) ProtoMessage() {}

func (x *CommitFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitFileRequest.ProtoReflect.Descriptor instead.
func (*CommitFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{5}
}

func (x *CommitFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CommitFileRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *CommitFileRequest) GetChunkLocations() map[string]*NodeList {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

// Client -> NameNode
type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_fractal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// NameNode -> Client
type GetFileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkLocations map[string]*NodeList   `protobuf:"bytes,1,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_fractal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileResponse) GetChunkLocations() map[string]*NodeList {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_fractal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_proto_fractal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type SwapFileNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapFileNameRequest) Reset() {
	*x = SwapFileNameRequest{}
	mi := &file_proto_fractal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapFileNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapFileNameRequest) ProtoMessage() {}

func (x *SwapFileNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapFileNameRequest.ProtoReflect.Descriptor instead.
func (*SwapFileNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{10}
}

func (x *SwapFileNameRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *SwapFileNameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

// DataNode -> NameNode
type HeartbeatMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	DiskUsage      int64                  `protobuf:"varint,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	DiskCapacity   int64                  `protobuf:"varint,4,opt,name=disk_capacity,json=diskCapacity,proto3" json:"disk_capacity,omitempty"`
	StoredChunkIds []string               `protobuf:"bytes,5,rep,name=stored_chunk_ids,json=storedChunkIds,proto3" json:"stored_chunk_ids,omitempty"` // The Master uses this to verify the Worker hasn't lost data
	RackId         string                 `protobuf:"bytes,6,opt,name=rack_id,json=rackId,proto3" json:"rack_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	mi := &file_proto_fractal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatMsg) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatMsg) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartbeatMsg) GetDiskUsage() int64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *HeartbeatMsg) GetDiskCapacity() int64 {
	if x != nil {
		return x.DiskCapacity
	}
	return 0
}

func (x *HeartbeatMsg) GetStoredChunkIds() []string {
	if x != nil {
		return x.StoredChunkIds
	}
	return nil
}

func (x *HeartbeatMsg) GetRackId() string {
	if x != nil {
		return x.RackId
	}
	return ""
}

// Client -> NameNode
type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_fractal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{12}
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_fractal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{13}
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// NameNode -> Client
type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_fractal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{14}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

// CLient -> DataNode
type RetrieveChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveChunkRequest) Reset() {
	*x = RetrieveChunkRequest{}
	mi := &file_proto_fractal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveChunkRequest) ProtoMessage() {}

func (x *RetrieveChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveChunkRequest.ProtoReflect.Descriptor instead.
func (*RetrieveChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{15}
}

func (x *RetrieveChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

// Client -> DataNode
type CheckChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChunkRequest) Reset() {
	*x = CheckChunkRequest{}
	mi := &file_proto_fractal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChunkRequest) ProtoMessage() {}

func (x *CheckChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChunkRequest.ProtoReflect.Descriptor instead.
func (*CheckChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{16}
}

func (x *CheckChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

// DataNode -> Client
type CheckChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	SyzeBytes     int64                  `protobuf:"varint,2,opt,name=syze_bytes,json=syzeBytes,proto3" json:"syze_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChunkResponse) Reset() {
	*x = CheckChunkResponse{}
	mi := &file_proto_fractal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChunkResponse) ProtoMessage() {}

func (x *CheckChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChunkResponse.ProtoReflect.Descriptor instead.
func (*CheckChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{17}
}

func (x *CheckChunkResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckChunkResponse) GetSyzeBytes() int64 {
	if x != nil {
		return x.SyzeBytes
	}
	return 0
}

var File_proto_fractal_proto protoreflect.FileDescriptor

const file_proto_fractal_proto_rawDesc = "" +
	"\n" +
	"\x13proto/fractal.proto\x12\afractal\"Q\n" +
	"\x10StandardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\")\n" +
	"\bNodeList\x12\x1d\n" +
	"\n" +
	"worker_ips\x18\x01 \x03(\tR\tworkerIps\":\n" +
	"\tChunkData\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"M\n" +
	"\x11CreateFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\"\xc4\x01\n" +
	"\x12CreateFileResponse\x12X\n" +
	"\x0fchunk_locations\x18\x01 \x03(\v2/.fractal.CreateFileResponse.ChunkLocationsEntryR\x0echunkLocations\x1aT\n" +
	"\x13ChunkLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.fractal.NodeListR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x11CommitFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\x12W\n" +
	"\x0fchunk_locations\x18\x03 \x03(\v2..fractal.CommitFileRequest.ChunkLocationsEntryR\x0echunkLocations\x1aT\n" +
	"\x13ChunkLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.fractal.NodeListR\x05value:\x028\x01\"-\n" +
	"\x0eGetFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\xbe\x01\n" +
	"\x0fGetFileResponse\x12U\n" +
	"\x0fchunk_locations\x18\x01 \x03(\v2,.fractal.GetFileResponse.ChunkLocationsEntryR\x0echunkLocations\x1aT\n" +
	"\x13ChunkLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.fractal.NodeListR\x05value:\x028\x01\"0\n" +
	"\x11DeleteFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"/\n" +
	"\x12DeleteChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"K\n" +
	"\x13SwapFileNameRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"\xc8\x01\n" +
	"\fHeartbeatMsg\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x03R\tdiskUsage\x12#\n" +
	"\rdisk_capacity\x18\x04 \x01(\x03R\fdiskCapacity\x12(\n" +
	"\x10stored_chunk_ids\x18\x05 \x03(\tR\x0estoredChunkIds\x12\x17\n" +
	"\arack_id\x18\x06 \x01(\tR\x06rackId\"\x12\n" +
	"\x10ListFilesRequest\"H\n" +
	"\bFileInfo\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\x05R\n" +
	"chunkCount\"<\n" +
	"\x11ListFilesResponse\x12'\n" +
	"\x05files\x18\x01 \x03(\v2\x11.fractal.FileInfoR\x05files\"1\n" +
	"\x14RetrieveChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\".\n" +
	"\x11CheckChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"K\n" +
	"\x12CheckChunkResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"syze_bytes\x18\x02 \x01(\x03R\tsyzeBytes2\xf7\x03\n" +
	"\rMasterService\x12C\n" +
	"\n" +
	"CommitFile\x12\x1a.fractal.CommitFileRequest\x1a\x19.fractal.StandardResponse\x12E\n" +
	"\n" +
	"CreateFile\x12\x1a.fractal.CreateFileRequest\x1a\x1b.fractal.CreateFileResponse\x12C\n" +
	"\n" +
	"DeleteFile\x12\x1a.fractal.DeleteFileRequest\x1a\x19.fractal.StandardResponse\x12E\n" +
	"\x10GetFileLocations\x12\x17.fractal.GetFileRequest\x1a\x18.fractal.GetFileResponse\x12B\n" +
	"\tListFiles\x12\x19.fractal.ListFilesRequest\x1a\x1a.fractal.ListFilesResponse\x12A\n" +
	"\rSendHeartbeat\x12\x15.fractal.HeartbeatMsg\x1a\x19.fractal.StandardResponse\x12G\n" +
	"\fSwapFileName\x12\x1c.fractal.SwapFileNameRequest\x1a\x19.fractal.StandardResponse2\xa2\x02\n" +
	"\rWorkerService\x12E\n" +
	"\vDeleteChunk\x12\x1b.fractal.DeleteChunkRequest\x1a\x19.fractal.StandardResponse\x12D\n" +
	"\rRetrieveChunk\x12\x1d.fractal.RetrieveChunkRequest\x1a\x12.fractal.ChunkData0\x01\x12=\n" +
	"\n" +
	"StoreChunk\x12\x12.fractal.ChunkData\x1a\x19.fractal.StandardResponse(\x01\x12E\n" +
	"\n" +
	"CheckChunk\x12\x1a.fractal.CheckChunkRequest\x1a\x1b.fractal.CheckChunkResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_fractal_proto_rawDescOnce sync.Once
	file_proto_fractal_proto_rawDescData []byte
)

func file_proto_fractal_proto_rawDescGZIP() []byte {
	file_proto_fractal_proto_rawDescOnce.Do(func() {
		file_proto_fractal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fractal_proto_rawDesc), len(file_proto_fractal_proto_rawDesc)))
	})
	return file_proto_fractal_proto_rawDescData
}

var file_proto_fractal_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_fractal_proto_goTypes = []any{
	(*StandardResponse)(nil),     // 0: fractal.StandardResponse
	(*NodeList)(nil),             // 1: fractal.NodeList
	(*ChunkData)(nil),            // 2: fractal.ChunkData
	(*CreateFileRequest)(nil),    // 3: fractal.CreateFileRequest
	(*CreateFileResponse)(nil),   // 4: fractal.CreateFileResponse
	(*CommitFileRequest)(nil),    // 5: fractal.CommitFileRequest
	(*GetFileRequest)(nil),       // 6: fractal.GetFileRequest
	(*GetFileResponse)(nil),      // 7: fractal.GetFileResponse
	(*DeleteFileRequest)(nil),    // 8: fractal.DeleteFileRequest
	(*DeleteChunkRequest)(nil),   // 9: fractal.DeleteChunkRequest
	(*SwapFileNameRequest)(nil),  // 10: fractal.SwapFileNameRequest
	(*HeartbeatMsg)(nil),         // 11: fractal.HeartbeatMsg
	(*ListFilesRequest)(nil),     // 12: fractal.ListFilesRequest
	(*FileInfo)(nil),             // 13: fractal.FileInfo
	(*ListFilesResponse)(nil),    // 14: fractal.ListFilesResponse
	(*RetrieveChunkRequest)(nil), // 15: fractal.RetrieveChunkRequest
	(*CheckChunkRequest)(nil),    // 16: fractal.CheckChunkRequest
	(*CheckChunkResponse)(nil),   // 17: fractal.CheckChunkResponse
	nil,                          // 18: fractal.CreateFileResponse.ChunkLocationsEntry
	nil,                          // 19: fractal.CommitFileRequest.ChunkLocationsEntry
	nil,                          // 20: fractal.GetFileResponse.ChunkLocationsEntry
}
var file_proto_fractal_proto_depIdxs = []int32{
	18, // 0: fractal.CreateFileResponse.chunk_locations:type_name -> fractal.CreateFileResponse.ChunkLocationsEntry
	19, // 1: fractal.CommitFileRequest.chunk_locations:type_name -> fractal.CommitFileRequest.ChunkLocationsEntry
	20, // 2: fractal.GetFileResponse.chunk_locations:type_name -> fractal.GetFileResponse.ChunkLocationsEntry
	13, // 3: fractal.ListFilesResponse.files:type_name -> fractal.FileInfo
	1,  // 4: fractal.CreateFileResponse.ChunkLocationsEntry.value:type_name -> fractal.NodeList
	1,  // 5: fractal.CommitFileRequest.ChunkLocationsEntry.value:type_name -> fractal.NodeList
	1,  // 6: fractal.GetFileResponse.ChunkLocationsEntry.value:type_name -> fractal.NodeList
	5,  // 7: fractal.MasterService.CommitFile:input_type -> fractal.CommitFileRequest
	3,  // 8: fractal.MasterService.CreateFile:input_type -> fractal.CreateFileRequest
	8,  // 9: fractal.MasterService.DeleteFile:input_type -> fractal.DeleteFileRequest
	6,  // 10: fractal.MasterService.GetFileLocations:input_type -> fractal.GetFileRequest
	12, // 11: fractal.MasterService.ListFiles:input_type -> fractal.ListFilesRequest
	11, // 12: fractal.MasterService.SendHeartbeat:input_type -> fractal.HeartbeatMsg
	10, // 13: fractal.MasterService.SwapFileName:input_type -> fractal.SwapFileNameRequest
	9,  // 14: fractal.WorkerService.DeleteChunk:input_type -> fractal.DeleteChunkRequest
	15, // 15: fractal.WorkerService.RetrieveChunk:input_type -> fractal.RetrieveChunkRequest
	2,  // 16: fractal.WorkerService.StoreChunk:input_type -> fractal.ChunkData
	16, // 17: fractal.WorkerService.CheckChunk:input_type -> fractal.CheckChunkRequest
	0,  // 18: fractal.MasterService.CommitFile:output_type -> fractal.StandardResponse
	4,  // 19: fractal.MasterService.CreateFile:output_type -> fractal.CreateFileResponse
	0,  // 20: fractal.MasterService.DeleteFile:output_type -> fractal.StandardResponse
	7,  // 21: fractal.MasterService.GetFileLocations:output_type -> fractal.GetFileResponse
	14, // 22: fractal.MasterService.ListFiles:output_type -> fractal.ListFilesResponse
	0,  // 23: fractal.MasterService.SendHeartbeat:output_type -> fractal.StandardResponse
	0,  // 24: fractal.MasterService.SwapFileName:output_type -> fractal.StandardResponse
	0,  // 25: fractal.WorkerService.DeleteChunk:output_type -> fractal.StandardResponse
	2,  // 26: fractal.WorkerService.RetrieveChunk:output_type -> fractal.ChunkData
	0,  // 27: fractal.WorkerService.StoreChunk:output_type -> fractal.StandardResponse
	17, // 28: fractal.WorkerService.CheckChunk:output_type -> fractal.CheckChunkResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_fractal_proto_init() }
func file_proto_fractal_proto_init() {
	if File_proto_fractal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fractal_proto_rawDesc), len(file_proto_fractal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_fractal_proto_goTypes,
		DependencyIndexes: file_proto_fractal_proto_depIdxs,
		MessageInfos:      file_proto_fractal_proto_msgTypes,
	}.Build()
	File_proto_fractal_proto = out.File
	file_proto_fractal_proto_goTypes = nil
	file_proto_fractal_proto_depIdxs = nil
}
